# Generated by Django 3.1 on 2020-09-03 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, verbose_name='Colores')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Personaje')),
                ('tamaño', models.IntegerField(verbose_name='Tamaño')),
                ('cel', models.CharField(max_length=13, verbose_name='Celular')),
                ('mail', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mail')),
                ('colores', models.ManyToManyField(to='amigurumis.Color')),
                ('name_cte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amigurumis.cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['name'],
            },
        ),
    ]
